logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        register: false
        registerHealthCheck: false
      config:
        enabled: false
      host: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: countries-service
          uri: lb://countries-service
          predicates:
            - Path=/countries/**
          filters:
            - RewritePath=/countries/(?<path>.*), /countries/$\{path}
        - id: songs-service
          uri: lb://songs
          predicates:
            - Path=/songs/**
          filters:
           - RewritePath=/songs/(?<path>.*), /songs/$\{path}
        - id: combo-service
          uri: lb://combo-service
          predicates:
            - Path=/combo/**
          filters:
            - RewritePath=/combo/(?<path>.*), /combo/$\{path}
        - id: auth-service
          uri: http://localhost:9100
          predicates:
           - Path=/sign-up/**
           - Path=/auth/**
           - Method=POST
          filters:
           - RewritePath=/sign-up/(?<path>.*), /sign-up/$\{path}
           - RewritePath=/auth/(?<path>.*), /auth/$\{path}